logger:
  default:
  - writer: console
    level: info
  - writer: file
    level: debug
    filename: ./logs/default.log
    maxsize: 10
    maxage: 15
    maxbackups: 5
    localtime: true
    compress: true

gateway:
  enable: true
  listen_addr: ":8080"

global:
  allocatable:
    gpu_memory: 16G

apps:
- name: llm-qwen3
  command:
    workdir: ./
    command: "python3"
    args:
    - "-m"
    - "http.server"
    - "809{{index}}"
    envs:
    - key: APP_NAME
      value: qwen3_{{index}}
    - key: PORT
      value: "809{{index}}"
  restart:
    # max_retries: 3
    interval: 5s
  replica:
    require:
      gpu_memory: 4G
    max_replicas: 2
    min_replicas: 1
  gateway_backends:
    - path_prefix: "/qwen3"
      backend: "127.0.0.1:809{{index}}"
      health_check:
        path: "/health"
        interval: 2s
        timeout: 1s
        healthy_threshold: 1
        unhealthy_threshold: 1

# - name: echo-app
#   command:
#     workdir: ./
#     command: "echo"
#     args:
#     - "Instance {{index}} started on port 909{{index}}"
#     envs: []
#   restart:
#     max_retries: 0
#   replica:
#     static: 3
#     require:
#       gpu_memory: 0